version: "3"

services:
  db:
    image: postgres:14
    # container_name: postgres
    ports:
      # - 5432:5432
      - 5532:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./pg:/tmp/pg
      #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #- ./db/logs:/var/log
    environment:
      #- POSTGRES_USER=postgres
      #- POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passw@rd
      #- PGDATA=/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      # - 8025:8025
      # - 1025:1025
      - 8125:8025
      - 1125:1025
volumes:
  db-store:
  redis-data:
