version: "3"

services:
  db:
    image: postgres:14
    # container_name: postgres
    ports:
      - 5432:5432
      # - 5732:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./pg:/tmp/pg
      #- ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      #- ./db/logs:/var/log
    environment:
      #- POSTGRES_USER=postgres
      #- POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=passw@rd
      #- PGDATA=/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - 6379:6379
      # - 6579:6379
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
      # - 8225:8025
      # - 1225:1025
volumes:
  db-store:
  redis-data:
