version: "3"

services:
  db:
    image: postgres:14
    # container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      # - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./db/logs:/var/log
    environment:
      # - POSTGRES_USER=postgres
      # - POSTGRES_DB: postgres
      - POSTGRES_PASSWORD=passw@rd
      # - PGDATA /var/lib/postgresql/data
volumes:
  db-store:
